name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Ou la version de Node.js que vous utilisez
      - name: Install dependencies
        run: npm install
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ce572518d97734ba1cf255a739c31268844cbdbceb6b3a93bff1570966bb4ebc5-a637b94a-7976-4b9d-be44-e3800b9d42a801e236970
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Utilisé pour les intégrations GitHub (i.e. commentaires de PR)
          action: "upload"
          app_location: "/" # Chemin vers le code source de l'application, utilisez "/" si c'est à la racine
          api_location: "/chatbot" # Chemin vers le code source de l'API
          output_location: "" # Répertoire de sortie après la construction de l'API
